baseURL: "https://brettinternet.com/slides/"
title: "slides"
description: "my talks and slides"
theme: "hugo-slides"

params:
  repo: "https://github.com/brettinternet/slides"
  author:
    name: "@brettinternet"
    homepage: "https://brettinternet.com"
  highlightjs:
    theme: "github"
  revealjs:
    hash: true
    theme: "dark"
  firebase:
    api_key: "AIzaSyB_irRP1uSwfjOH0Sa5p_p8w1F38ZHy6qA"
    auth_domain: "slides-d5c14.firebaseapp.com"
    database_url: "https://slides-d5c14.firebaseio.com"
    project_id: "slides-d5c14"
    sotrage_bucket: "slides-d5c14.appspot.com"
    messaging_sender_id: "1085061633013"
    app_id: "1:1085061633013:web:150eec1fbc4727aaf5c6bc"
    measurement_id: "G-Z0MK6965VJ"
  presenter_uids: ["SjD1ze42kKP7ep9iGeZEqd6dNrv2"]
