baseURL: https://brettinternet.com/slides
languageCode: en-us
title: slides
author: brett

theme: reveal-hugo

module:
  mounts:
    - source: static
      target: static
    # Unable to reference node_modules from head partial inserted into theme
    # Probably related: https://github.com/gohugoio/hugo/issues/6274
    # https://discourse.gohugo.io/t/resources-concat-with-js-slice-interface-not-supported-in-concat/26558/6
    - source: node_modules/firebaseui/dist/firebaseui.css
      target: static/firebaseui.css
    - source: node_modules/reveal.js-plugins/chalkboard/plugin.js
      target: static/plugins/chalkboard.js
    - source: node_modules/reveal.js-plugins/chalkboard/style.css
      target: static/plugins/chalkboard.css
    - source: node_modules/reveal.js-plugins/chalkboard/img/
      target: static/plugins/img/

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true

outputFormats:
  Reveal:
    baseName: index
    mediaType: text/html
    isHTML: true

params:
  reveal_hugo:
    theme: moon
    # https://highlightjs.org/static/demo/
    highlight_theme: solarized-dark
