name: Deploy

on:
  push:
    branches:
      - master

jobs:
  publish:
    # api: https://developer.github.com/webhooks/event-payloads/
    if: "!contains(github.event.head_commit.message, 'skipci')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Git
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Set build version & time
        run: |
          echo ::set-env name=BUILD_VERSION::$(echo $GITHUB_SHA | cut -c 1-6)
          echo ::set-env name=BUILD_TIME::$(date --iso-8601=seconds)

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production
          PATH_PREFIX: /slides

      # source: https://github.com/tschaub/gh-pages/issues/345#issuecomment-608243163
      - name: Deploy site
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -u "$GITHUB_ACTOR@users.noreply.github.com" -m "deploy revision $BUILD_VERSION"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
