name: Deploy

on:
  push:
    branches:
      - master

jobs:
  publish:
    # api: https://developer.github.com/webhooks/event-payloads/
    if: "!contains(github.event.head_commit.message, 'skipci')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Git
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Set build version & time
        run: |
          echo "BUILD_VERSION=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
          echo "BUILD_TIME=$(date --iso-8601=seconds)" >> $GITHUB_ENV

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production
          PATH_PREFIX: /slides/
          THEME: black
          HIGHLIGHT_THEME: agate
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: slides-d5c14.firebaseapp.com
          FIREBASE_DATABASE_URL: https://slides-d5c14.firebaseio.com
          FIREBASE_APP_ID: 1:1085061633013:web:150eec1fbc4727aaf5c6bc
          FIREBASE_PROJECT_ID: slides-d5c14
          FIREBASE_MEASUREMENT_ID: G-Z0MK6965VJ
          PRESENTER_UIDS: [SjD1ze42kKP7ep9iGeZEqd6dNrv2]

      # source: https://github.com/tschaub/gh-pages/issues/345#issuecomment-608243163
      - name: Deploy site
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -u "$GITHUB_ACTOR@users.noreply.github.com" -m "deploy revision $BUILD_VERSION"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
